apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dpl
spec:
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      nodeSelector: 
        kubernetes.io/hostname: node4 
      containers:
      - name: postgres-app
        image: postgres:latest
        ports:
        - containerPort: 5432

      # The usage of when we not use the exact needed of the secret
        env: 
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                  key: WHATEVER_USER
                  name: postgres-demo-cm

        envFrom:
          - configMapRef:
              name: postgres-demo-cm
