apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  # labels:
  #   app.kubernetes.io/name: myingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingressClassName: "nginx"
spec:
  ingressClassName: nginx 
  tls:
  - hosts: 
    - nginx-k8s-demo.vuthytourn.shop
    secretName: nginx-k8s-secretname
  rules:
  - host: nginx-k8s-demo.vuthytourn.shop
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-svc
            port: 
              number: 80
